# Generated by Django 2.0.2 on 2018-03-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interested_in_domains',
            field=models.ManyToManyField(blank=True, to='app.Domain'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='app.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tools',
            field=models.ManyToManyField(blank=True, to='app.Tool'),
        ),
    ]
