# Generated by Django 2.0.2 on 2018-03-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180304_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'specialties'},
        ),
    ]
