# Generated by Django 2.0.2 on 2018-03-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180304_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_designer',
            field=models.BooleanField(default=False, verbose_name='is a designer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='is a developer'),
        ),
    ]
