# Generated by Django 2.0.2 on 2018-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180304_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='are_members_needed',
            field=models.BooleanField(default=True, verbose_name='are members needed?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_needed',
            field=models.BooleanField(default=False),
        ),
    ]
