# Generated by Django 2.0.2 on 2018-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180304_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
    ]
