# Generated by Django 2.0.2 on 2018-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
